language: c++
compiler: gcc
sudo: true
env:
os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: TARGET="linux64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - gdb

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: TARGET="osx"


  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc


before_install:
  - pushd ${HOME}
  - wget http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_osx_release.zip -O /tmp/of_v0.9.8_osx_release.tar.gz
  - tar xzf /tmp/of_v0.9.8_osx_release.tar.gz
  - mv of_v0.9.8_osx_release/ openframeworks
  - popd
  - if [ "$TARGET" == "linux64" ]; then
          sudo ${HOME}/openframeworks/scripts/linux/ubuntu/install_dependencies.sh;
          sudo ${HOME}/openframeworks/scripts/linux/ubuntu/install_codecs.sh;
      elif [ "$TARGET" == "osx" ]; then
          scripts/linux/download_libs.sh -a armv6l;
      fi


install:
  - ./install_deps.sh


script:
  - make Release